blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/mildman1848/metadata.artists.audible/blob/main/README.md
    about: Please read the setup and release documentation first.
